# modules/module_generator_module.py
"""
Self-Evolution Engine — JAN can create new modules for itself.
When JAN encounters a task it can't handle:
1. Recognizes the gap
2. Asks user: "Shall I add this capability?"
3. Researches how to do it (via research_agent)
4. Generates Python module code from a template
5. Saves to modules/generated/ and hot-loads it
6. Registers the new module with the orchestrator
"""
import os
import json
import importlib
import importlib.util
import re
import requests
import textwrap
from datetime import datetime
from pathlib import Path
from .base import ModuleBase


# Template for auto-generated modules
MODULE_TEMPLATE = '''# modules/generated/{filename}
# Auto-generated by JAN Module Generator on {timestamp}
# Purpose: {description}
"""
{docstring}
"""
import os
import json
{extra_imports}
from modules.base import ModuleBase


class {class_name}(ModuleBase):
    """{short_description}"""

    def __init__(self):
        super().__init__("{module_name}")
{init_body}

{methods}

    def process(self, input_data):
        action = input_data.get("action", "{default_action}")
{process_body}
'''


class ModuleGeneratorModule(ModuleBase):
    """JAN's self-evolution engine — generates and loads new modules dynamically."""

    OLLAMA_URL = "http://localhost:11434/api/chat"
    GENERATED_DIR = Path("modules/generated")

    def __init__(self):
        super().__init__("module_generator")
        self.GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        self.research_agent = None  # wired from __init__.py
        self.memory = None  # wired from __init__.py
        self.orchestrator = None  # wired from __init__.py
        self._loaded_modules = {}  # track dynamically loaded modules

    def _generate_code_with_llm(self, task_description, research_context=""):
        """Ask the local LLM to generate module code."""
        prompt = f"""You are a Python code generator for JAN (an AI assistant framework).
Generate a complete, working Python module class that extends ModuleBase.

TASK: {task_description}

{f"RESEARCH CONTEXT (use this info to write better code):{chr(10)}{research_context}" if research_context else ""}

RULES:
1. The class must extend ModuleBase (from modules.base import ModuleBase)
2. The __init__ must call super().__init__("module_name")
3. Must have a process(self, input_data) method that handles different actions
4. input_data is always a dict with at least an "action" key
5. Return dicts with "status": "ok" on success, or "error": "message" on failure
6. Use try/except for external operations
7. Keep it simple and focused on ONE capability
8. Use standard library or common pip packages only
9. Add docstrings

Respond with ONLY a JSON object in this format:
{{
    "module_name": "short_snake_case_name",
    "class_name": "PascalCaseName",
    "description": "What this module does",
    "code": "complete Python code as a string",
    "pip_packages": ["list", "of", "required", "pip", "packages"],
    "schema": {{
        "description": "module description for the LLM",
        "input": {{"action": "string", ...other params...}},
        "output": {{"status": "ok", ...}}
    }}
}}"""

        try:
            resp = requests.post(self.OLLAMA_URL, json={
                "model": "llama3.1:8b",
                "messages": [
                    {"role": "system", "content": "You are a Python module code generator. Respond ONLY with valid JSON. No markdown, no explanation."},
                    {"role": "user", "content": prompt}
                ],
                "stream": False,
                "options": {"temperature": 0.4, "num_predict": 2048}
            }, timeout=180)
            raw = resp.json()["message"]["content"]

            # Parse JSON from response
            text = raw.strip()
            if text.startswith("```"):
                lines = text.split("\n")
                lines = [l for l in lines if not l.strip().startswith("```")]
                text = "\n".join(lines)

            start = text.find("{")
            end = text.rfind("}") + 1
            if start != -1 and end > start:
                return json.loads(text[start:end]), None

            return None, "LLM did not return valid JSON"
        except json.JSONDecodeError as e:
            return None, f"Failed to parse LLM output: {str(e)}"
        except Exception as e:
            return None, f"LLM error: {str(e)}"

    def _validate_code(self, code):
        """Basic safety checks on generated code."""
        dangerous_patterns = [
            r"os\.system\s*\(",
            r"subprocess\.call\s*\(.*shell\s*=\s*True",
            r"eval\s*\(",
            r"exec\s*\(",
            r"__import__\s*\(",
            r"shutil\.rmtree\s*\(.*/",  # prevent recursive deletes of system dirs
        ]
        warnings = []
        for pattern in dangerous_patterns:
            if re.search(pattern, code):
                warnings.append(f"Potentially dangerous pattern detected: {pattern}")

        # Syntax check
        try:
            compile(code, "<generated>", "exec")
        except SyntaxError as e:
            return False, f"Syntax error in generated code: {str(e)}", warnings

        return True, None, warnings

    def _save_module(self, module_name, code, metadata):
        """Save generated module to disk."""
        filename = f"{module_name}_module.py"
        filepath = self.GENERATED_DIR / filename
        
        # Add metadata header
        header = f"# Auto-generated by JAN on {datetime.now().isoformat()}\n"
        header += f"# Description: {metadata.get('description', 'N/A')}\n"
        header += f"# Pip packages: {metadata.get('pip_packages', [])}\n\n"

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(header + code)

        # Save metadata alongside
        meta_path = self.GENERATED_DIR / f"{module_name}_module.meta.json"
        with open(meta_path, "w", encoding="utf-8") as f:
            json.dump({
                "module_name": module_name,
                "class_name": metadata.get("class_name", ""),
                "description": metadata.get("description", ""),
                "pip_packages": metadata.get("pip_packages", []),
                "schema": metadata.get("schema", {}),
                "created_at": datetime.now().isoformat(),
                "filename": filename
            }, f, indent=2)

        return str(filepath)

    def _install_packages(self, packages):
        """Install required pip packages."""
        if not packages:
            return {"status": "ok", "installed": []}
        
        import subprocess
        installed = []
        errors = []
        for pkg in packages:
            try:
                subprocess.check_call(
                    ["pip", "install", pkg, "--quiet"],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                    timeout=60
                )
                installed.append(pkg)
            except Exception as e:
                errors.append(f"{pkg}: {str(e)}")

        return {"status": "ok" if not errors else "partial", "installed": installed, "errors": errors}

    def _load_module(self, module_name, class_name, filepath):
        """Dynamically load a generated module."""
        try:
            spec = importlib.util.spec_from_file_location(
                f"modules.generated.{module_name}_module",
                filepath
            )
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)

            # Get the class
            cls = getattr(mod, class_name)
            instance = cls()
            self._loaded_modules[module_name] = instance
            return instance, None
        except Exception as e:
            return None, f"Failed to load module: {str(e)}"

    def _register_with_orchestrator(self, module_name, instance, schema):
        """Register the new module with JAN's orchestrator so the LLM can use it."""
        if self.orchestrator:
            self.orchestrator.modules_registry[module_name] = instance
            self.orchestrator.schemas[module_name] = schema
            return True
        return False

    # ========================
    # Main Actions
    # ========================
    def generate_module(self, task_description, auto_install=True):
        """Full pipeline: research → generate → validate → save → load → register."""
        result = {
            "task": task_description,
            "status": None,
            "module_name": None,
            "steps": []
        }

        # Step 1: Research (if research_agent available)
        research_context = ""
        if self.research_agent:
            try:
                research = self.research_agent.research(
                    f"Python code to {task_description}",
                    strategy="duckduckgo",
                    save_to_memory=False
                )
                if research.get("answer"):
                    research_context = research["answer"]
                    result["steps"].append("✅ Researched online")
            except Exception:
                result["steps"].append("⚠️ Research skipped")

        # Step 2: Generate code with LLM
        gen_data, err = self._generate_code_with_llm(task_description, research_context)
        if err:
            result["status"] = "failed"
            result["error"] = f"Code generation failed: {err}"
            return result
        result["steps"].append("✅ Code generated by LLM")

        module_name = gen_data.get("module_name", "custom_module")
        class_name = gen_data.get("class_name", "CustomModule")
        code = gen_data.get("code", "")
        pip_packages = gen_data.get("pip_packages", [])
        schema = gen_data.get("schema", {
            "description": gen_data.get("description", task_description),
            "input": {"action": "string"},
            "output": {"status": "ok"}
        })

        # Step 3: Validate code
        valid, syntax_err, warnings = self._validate_code(code)
        if not valid:
            result["status"] = "failed"
            result["error"] = f"Code validation failed: {syntax_err}"
            return result
        result["steps"].append(f"✅ Code validated" + (f" (warnings: {warnings})" if warnings else ""))

        # Step 4: Install pip packages
        if auto_install and pip_packages:
            install_result = self._install_packages(pip_packages)
            result["steps"].append(f"✅ Packages installed: {install_result.get('installed', [])}")
            if install_result.get("errors"):
                result["steps"].append(f"⚠️ Package errors: {install_result['errors']}")

        # Step 5: Save module
        filepath = self._save_module(module_name, code, gen_data)
        result["steps"].append(f"✅ Saved to {filepath}")

        # Step 6: Load module
        instance, load_err = self._load_module(module_name, class_name, filepath)
        if load_err:
            result["status"] = "partial"
            result["error"] = f"Saved but couldn't load: {load_err}"
            result["module_name"] = module_name
            return result
        result["steps"].append("✅ Module loaded")

        # Step 7: Register with orchestrator
        registered = self._register_with_orchestrator(module_name, instance, schema)
        if registered:
            result["steps"].append("✅ Registered with orchestrator — JAN can now use it")
        else:
            result["steps"].append("⚠️ Orchestrator not available — module loaded but not registered")

        # Step 8: Save to memory
        if self.memory:
            try:
                self.memory.save_knowledge(
                    topic=f"module:{module_name}",
                    content=f"Generated module '{module_name}' for: {task_description}. Schema: {json.dumps(schema)}",
                    source="module_generator"
                )
            except Exception:
                pass

        result["status"] = "ok"
        result["module_name"] = module_name
        result["class_name"] = class_name
        result["schema"] = schema
        return result

    def list_generated(self):
        """List all generated modules."""
        modules = []
        for meta_file in self.GENERATED_DIR.glob("*.meta.json"):
            try:
                with open(meta_file, "r", encoding="utf-8") as f:
                    meta = json.load(f)
                    meta["loaded"] = meta.get("module_name", "") in self._loaded_modules
                    modules.append(meta)
            except Exception:
                continue
        return {"status": "ok", "modules": modules, "count": len(modules)}

    def load_all_generated(self):
        """Load all previously generated modules on startup."""
        loaded = []
        errors = []
        for meta_file in self.GENERATED_DIR.glob("*.meta.json"):
            try:
                with open(meta_file, "r", encoding="utf-8") as f:
                    meta = json.load(f)
                module_name = meta["module_name"]
                class_name = meta["class_name"]
                filepath = self.GENERATED_DIR / meta["filename"]

                if filepath.exists():
                    instance, err = self._load_module(module_name, class_name, str(filepath))
                    if instance:
                        self._register_with_orchestrator(
                            module_name, instance, meta.get("schema", {})
                        )
                        loaded.append(module_name)
                    else:
                        errors.append(f"{module_name}: {err}")
            except Exception as e:
                errors.append(str(e))

        return {"status": "ok", "loaded": loaded, "errors": errors}

    def delete_module(self, module_name):
        """Delete a generated module."""
        filepath = self.GENERATED_DIR / f"{module_name}_module.py"
        meta_path = self.GENERATED_DIR / f"{module_name}_module.meta.json"

        deleted = []
        if filepath.exists():
            os.remove(filepath)
            deleted.append(str(filepath))
        if meta_path.exists():
            os.remove(meta_path)
            deleted.append(str(meta_path))

        # Unregister from orchestrator
        if self.orchestrator and module_name in self.orchestrator.modules_registry:
            del self.orchestrator.modules_registry[module_name]
            if module_name in self.orchestrator.schemas:
                del self.orchestrator.schemas[module_name]

        if module_name in self._loaded_modules:
            del self._loaded_modules[module_name]

        if deleted:
            return {"status": "ok", "deleted": deleted}
        return {"error": f"Module '{module_name}' not found in generated modules"}

    def process(self, input_data):
        action = input_data.get("action", "generate")

        if action == "generate":
            task = input_data.get("task", input_data.get("description", ""))
            if not task:
                return {"error": "Missing 'task' — describe what capability you want to add"}
            return self.generate_module(
                task,
                auto_install=input_data.get("auto_install", True)
            )

        elif action == "list":
            return self.list_generated()

        elif action == "load_all":
            return self.load_all_generated()

        elif action == "delete":
            name = input_data.get("module_name", "")
            if not name:
                return {"error": "Missing 'module_name' to delete"}
            return self.delete_module(name)

        else:
            return {"error": f"Unknown action: {action}. Use: generate, list, load_all, delete"}
